### ISSUE TITLE
implement logging on failure in run class (moved there from run_all)

### ISSUE THREAD

**Issue by ClemensBuechner** [aibasel/machetli#57]

**Comment by FlorianPommerening** [comment]
The reason for this functionality was mainly to be nice to the file system on the grid (i.e., don't write files unless it is necessary). This might be premature optimization, so we decided to close the issue and reopen it (or create a new one) only if it becomes a problem. We now also create run directories in all environments, so storing log files inside each of them is natural and helps with debugging. Currently, the functionality is not implemented and documented as not working, so removing it completely won't be a big loss. We can still easily decide to always log the output of a call or never log it. If a particular evaluator wants to do something more complex, this still can be implemented there but we don't see this as relevant to offer as a general functionality.
