### ISSUE TITLE
refactor error handling

### ISSUE THREAD

**Issue by ClemensBuechner** [aibasel/machetli#72]
- Error reporting should not be part of error classes. Implement like standard errors in python and use the message member.
- abort should always lead to logging.critical
- There's too much logic in the exceptions.

**Comment by FlorianPommerening** [comment]
One more point from #65: we could move some of the error-handling logic from the environment to the search, so we don't have to duplicate it.

**Comment by FlorianPommerening** [comment]
# Program Error in the search ("this cannot happen" type errors) and errors when creating successors:
  * `logging.critical`

# SubmissionError (could not submit job)
  * raise in environment
  * catch and handle in search as `logging.critical`

# PollingError (could not access state of submitted job)
  * wait & retry before raising
  * catch and handle in search as `logging.critical`

# EvaluatorError (evaluator did not finish)
  * raise in code that calls evaluator
  * catch and handle in search
  * Timeout/Memout
    * in deterministic mode: stop search with error explaining this
    * in non-deterministic mode: record error and print if no improving successor was found in the other successors
  * evaluator script crashes
    * in deterministic mode: stop search with error explaining this
    * in non-deterministic mode: keep run log in run dirs, directly print run_dir of failed run (don't print the error)

# TaskError (grid job in critical state)
  * raise in environment
  * handle in the same way as EvaluatorError

# No Result File 
  * wait & retry before raising
  * raise in environment
  * handle in the same way as EvaluatorError

# UnpickleError
  * raise in read_state
  * handle in code that executes evaluator


# Before search is stopped with `logging.critical`
  * keep run_dirs
    * pickled state
    * logs (run.log, run.err)
  * print current incumbent
  * print list of failed runs

# Allow restarting from failed search
  * use run directories, store incumbent
  * When starting the search, check if data directory is present
  * if so, ask then
    a) remove data directory and start from scratch
    b) load incumbent and start search from there

**Comment by FlorianPommerening** [comment]
#89 fixes most of the cases above. We decided to create follow-up issues for restarting the search, and dealing with out-of-resources errors because both of these will need more changes in the way evaluators are called.
