### ISSUE TITLE
Remove cmd_name from the Parser's add_pattern method and add parser argument to the Run's constructor

### ISSUE THREAD

**Issue by galerykaeser** [aibasel/machetli#9]
Currently, the [add_pattern method](https://github.com/aibasel/minimizer/blob/1ab638a82def7a14e42daae8c60efb4bbb3e989c/minimizer/parser.py#L45) of the parser class has an argument ```cmd_names```, which accepts one or multiple [run](https://github.com/aibasel/minimizer/blob/1ab638a82def7a14e42daae8c60efb4bbb3e989c/minimizer/run.py#L12) object names (as, e.g., defined and used [here](https://github.com/aibasel/minimizer/blob/1ab638a82def7a14e42daae8c60efb4bbb3e989c/examples/toy_problem/grid_test.py#L97-L99)). Storing the names of the runs inside a parser object creates an unnecessary coupling between a parser and the run(s). The parser does not need to know anything about the run(s) it should be used for.

Improvement suggestion: Remove the ```cmd_names``` argument from ```add_pattern``` and add a ```parsers``` argument to the constructor of the run class. This way, each run has an internal list containing the parser(s) to be applied to its output.

**Comment by FlorianPommerening** [comment]
We now decoupled parsing the output from running the code, so this is no longer applicable.
